# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile 

BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM1
ARDUINO_LIBS = Ethernet Ethernet/utility SPI aJson aJson/utility MemoryFree

include $(ARDMK_DIR)/arduino-mk/Arduino.mk
